{{- if .Values.rbac.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: {{ .Values.rbac.serviceAccount.automountServiceAccountToken }}
metadata:
  name: {{ include "bar-service.serviceAccountName" . }}
  labels:
    {{- include "bar-service.labels" . | nindent 4 }}
    {{- with .Values.rbac.serviceAccount.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.rbac.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  namespace: {{ include "bar-service.namespace" . }}
{{- end }}
